from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

import requests

logger = logging.getLogger(__name__)


class DiscordReportError(RuntimeError):
    """Raised when Discord report delivery fails."""


class DiscordReporter:
    """Send StreamPilot report summaries to Discord via webhook."""

    def __init__(self, webhook_url: str | None = None, timeout_seconds: int = 10):
        self.webhook_url = webhook_url or os.getenv("DISCORD_REPORT_WEBHOOK_URL", "").strip()
        self.timeout_seconds = timeout_seconds

    @property
    def enabled(self) -> bool:
        return bool(self.webhook_url)

    def send_markdown_report(
        self,
        report_path: str | Path,
        summary: dict[str, Any],
        attach_report: bool = True,
    ) -> bool:
        if not self.enabled:
            logger.info("Discord reporting skipped: webhook not configured")
            return False

        report_file = Path(report_path)
        if not report_file.exists():
            raise DiscordReportError(f"Report file does not exist: {report_file}")

        payload = {
            "username": "StreamPilot",
            "embeds": [self._build_embed(summary)],
        }

        try:
            if attach_report:
                files = {
                    "file": (
                        report_file.name,
                        report_file.read_bytes(),
                        "text/markdown",
                    )
                }
                data = {"payload_json": json.dumps(payload)}
                response = requests.post(
                    self.webhook_url,
                    data=data,
                    files=files,
                    timeout=self.timeout_seconds,
                )
            else:
                response = requests.post(
                    self.webhook_url,
                    json=payload,
                    timeout=self.timeout_seconds,
                )

            if response.status_code >= 300:
                raise DiscordReportError(
                    f"Discord webhook failed with status {response.status_code}: {response.text[:300]}"
                )

            logger.info("Discord report sent successfully")
            return True

        except requests.RequestException as exc:
            raise DiscordReportError(f"Discord webhook request failed: {exc}") from exc

    def _build_embed(self, summary: dict[str, Any]) -> dict[str, Any]:
        fields = [
            {"name": "Category", "value": str(summary.get("category", "Unknown")), "inline": True},
            {"name": "Duration", "value": str(summary.get("duration", "Unknown")), "inline": True},
            {
                "name": "Stream Score",
                "value": str(summary.get("stream_score", "Unknown")),
                "inline": True,
            },
            {
                "name": "Avg Viewers",
                "value": str(summary.get("average_viewers", "Unknown")),
                "inline": True,
            },
            {
                "name": "Peak Viewers",
                "value": str(summary.get("peak_viewers", "Unknown")),
                "inline": True,
            },
            {
                "name": "Chat Messages",
                "value": str(summary.get("human_messages", "Unknown")),
                "inline": True,
            },
            {
                "name": "Unique Chatters",
                "value": str(summary.get("unique_chatters", "Unknown")),
                "inline": True,
            },
            {
                "name": "Session",
                "value": str(summary.get("session_id", "Unknown")),
                "inline": False,
            },
        ]

        highlights = summary.get("highlights") or []
        if highlights:
            fields.append(
                {
                    "name": "Top Moments",
                    "value": "\n".join(f"• {item}" for item in highlights[:5])[:1000],
                    "inline": False,
                }
            )

        tips = summary.get("tips") or []
        if tips:
            fields.append(
                {
                    "name": "Next Stream Tips",
                    "value": "\n".join(f"• {item}" for item in tips[:5])[:1000],
                    "inline": False,
                }
            )

        return {
            "title": f"📊 {summary.get('title', 'Stream Complete')}",
            "description": "Report generated by StreamPilot — Never Stream Alone.",
            "color": 3447003,
            "fields": fields,
        }
